apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  # namespace: wandarlust-namespace
  labels:
    app: {{ .Values.appName }}
  {{- if .Values.serviceAnnotations }}
  annotations:
    {{- toYaml .Values.serviceAnnotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
      name: http
  selector:
    app: {{ .Values.appName }}