version: "3.9"

services:

  backend:
    # build:
    #   context: ./backend
    image: atiyadocker/wanderlust-backend:${SHA:-latest}
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/wanderlust
      - REDIS_URL=redis://redis:6379
    # env_file:
    #   - ./backend/.env
    depends_on:
      - mongodb
      - redis
    networks:
      - wanderlust-network

  mongodb:
    image: mongo:7.0.34-jammy
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - wanderlust-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - wanderlust-network

  frontend:
    # build:
    #   context: ./frontend
    image: atiyadocker/wanderlust-frontend:${SHA:-latest}
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - wanderlust-network
  nginx:
    # build:
    #   context: ./nginx
    image: atiyadocker/wanderlust-nginx:${SHA}
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend  
      - backend
    networks:
      - wanderlust-network

volumes:
  mongodb-data:
  redis-data:

networks:
  wanderlust-network: