apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  # namespace: wandarlust-namespace
  labels:
    app: wandarlust-frontend

data:
  VITE_API_PATH: ""
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  # namespace: wandarlust-namespace
  labels:
    app: wandarlust-frontend
spec:
  type: ClusterIP
  ports:
    - port: 5173
      targetPort: 5173
      name: http
  selector:
    app: wandarlust-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  # namespace: wandarlust-namespace
  labels:
    app: wandarlust-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wandarlust-frontend
  template:
    metadata:
      labels:
        app: wandarlust-frontend
    spec:
      imagePullSecrets:
      - name: my-docker-key
      containers:
        - name: wandarlust-frontend
          image: 972011045435.dkr.ecr.us-east-1.amazonaws.com/wandarlust-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
              name: http
          envFrom:
            - configMapRef:
                name: frontend-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"