name: Docker Image CI/CD

on: 
  push:
    branches: [main, staging]
  pull_request: 
    branches: [main, staging]

jobs:
  validate:
    runs-on: self-hosted
    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
      redis:
        image: redis:7
        ports:
          - 6379:6379
    env:
      MONGODB_URI: mongodb://localhost:27017/wanderlust_test
      REDIS_URL: redis://localhost:6379
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installing Backend dependencies
        run: |
          cd backend
          npm ci   


      - name: Linting Backend
        run: |
          cd backend
          npm run lint

      - name: Testing backend
        run: |
          cd backend
          npm test -- --detectOpenHandles --runInBand
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Gitleaks (Docker approach)
        run: |
          docker pull zricethezav/gitleaks:latest > /dev/null 2>&1
          docker run --rm -v "${{ github.workspace }}":/path zricethezav/gitleaks:latest detect --source="/path" --report-path=/path/gitleaks-report.json --exit-code=0

      - name: Install and run njsscan
        run: |
          python -m pip install --upgrade pip
          pip install njsscan
          njsscan --json -o njsscan-report.json ./backend || true

      - name: Install and run Semgrep
        run: |
          pip install semgrep
          semgrep scan --config="p/javascript" --config="p/owasp-top-ten" --json -o semgrep-report.json ./backend || true
      - name: Install and run Retire.js
        run: |
          sudo npm install -g retire
          cd backend
          retire --outputformat json --outputpath ../retirejs-report.json || true
      # - name: Upload Reports to DefectDojo using Python Script
      #   if: always()
      #   run: |
      #     pip install requests
      #     [ -f gitleaks-report.json ] && python upload-file.py gitleaks-report.json "Gitleaks Scan"
      #     [ -f retirejs-report.json ] && python upload-file.py retirejs-report.json "Retire.js Scan"
      #     [ -f njsscan-report.json ] && python upload-file.py njsscan-report.json "SARIF"
      #     [ -f semgrep-report.json ] && python upload-file.py semgrep-report.json "Semgrep JSON Report"
          
  Docker:
    needs: validate
    runs-on: self-hosted
    if: github.event_name == 'push'
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Image
        run: |
          docker build \
          -f backend/Dockerfile \
          -t atiyaali/wanderlust-backend:${{ github.sha }} \
          -t atiyaali/wanderlust-backend:latest \
          backend
      
      - name: Build Frontend Image
        run: |
          docker build \
          -f frontend/Dockerfile \
          -t atiyaali/wanderlust-frontend:${{ github.sha }} \
          -t atiyaali/wanderlust-frontend:latest \
          frontend

      - name: Build Nginx Image
        run: |
          docker build \
          -f nginx/Dockerfile \
          -t atiyaali/wanderlust-nginx:${{ github.sha }} \
          -t atiyaali/wanderlust-nginx:latest \
          nginx

      # - name: Trivy scan frontend image
      #   run: |
      #     docker run --rm \
      #     -v /var/run/docker.sock:/var/run/docker.sock \
      #     aquasec/trivy:latest image \
      #     --timeout 15m \
      #     --scanners vuln \
      #     --db-repository ghcr.io/aquasecurity/trivy-db \
      #     atiyaali/wanderlust-frontend:${{ github.sha }}

      # - name: Trivy scan backend image
      #   run: |
      #     docker run --rm \
      #     -v /var/run/docker.sock:/var/run/docker.sock \
      #     aquasec/trivy:latest image \
      #     --timeout 15m \
      #     --scanners vuln \
      #     --db-repository ghcr.io/aquasecurity/trivy-db \
      #     atiyaali/wanderlust-backend:${{ github.sha }}

      # - name: Trivy scan nginx image
      #   run: |
      #     docker run --rm \
      #     -v /var/run/docker.sock:/var/run/docker.sock \
      #     aquasec/trivy:latest image \
      #     --timeout 15m \
      #     --scanners vuln \
      #     --db-repository ghcr.io/aquasecurity/trivy-db \
      #     atiyaali/wanderlust-nginx:${{ github.sha }}

      - name: Push backend image
        run: |
          docker push atiyaali/wanderlust-backend:${{ github.sha }}
          docker push atiyaali/wanderlust-backend:latest

      - name: Push frontend image
        run: |
          docker push atiyaali/wanderlust-frontend:${{ github.sha }}
          docker push atiyaali/wanderlust-frontend:latest

      - name: Push nginx image
        run: |
          docker push atiyaali/wanderlust-nginx:${{ github.sha }}
          docker push atiyaali/wanderlust-nginx:latest

  # deploy-eks:
  #   needs: Docker
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push'
  #   environment: staging
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4

  #     # 1. Install Deployment Tools
  #     - name: Install Deployment Tools
  #       run: |
  #         wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
  #         chmod +x /usr/local/bin/yq
  #         curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  #         curl -L https://github.com/helmfile/helmfile/releases/download/v0.165.0/helmfile_0.165.0_linux_amd64.tar.gz | tar xz
  #         sudo mv helmfile /usr/local/bin/
  #         helm plugin install https://github.com/databus23/helm-diff

  #     # 2. Update Image Tags specifically inside Helmcharts/values/
  #     # Update Image Tags in Helm Values
  #     - name: Update Image Tags in Helm Values
  #       run: |
  #         yq eval '.appVersion = "${{ github.sha }}"' -i Helmcharts/values/backendvalues.yaml
  #         yq eval '.appVersion = "${{ github.sha }}"' -i Helmcharts/values/frontendvalues.yaml
  #         yq eval '.appVersion = "${{ github.sha }}"' -i Helmcharts/values/nginxvalues.yaml

  #     # 3. Authenticate with AWS EKS
  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v2
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: us-east-1

  #     - name: Connect to AWS EKS
  #       run: |
  #         aws eks update-kubeconfig --region us-east-1 --name ${{ secrets.EKS_CLUSTER_NAME }}

  #     # 4. Execute Helmfile inside the Helmcharts directory
  #     - name: Helmfile Apply
  #       working-directory: ./Helmcharts
  #       run: |
  #         helmfile diff
  #         helmfile apply 




  